name: Telegram to GitHub Remote Upload
on:
  workflow_dispatch:
    inputs:
      file_url:
        description: 'የቴሌግራም ፋይል ሊንክ (Direct Link)'
        required: true
      file_name:
        description: 'የፋይሉ ስም (ለምሳሌ app.apk)'
        required: true

jobs:
  download_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Download File using Wget
        run: |
          wget --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" -O "${{ github.event.inputs.file_name }}" "${{ github.event.inputs.file_url }}"
      
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v1.0"
          files: ${{ github.event.inputs.file_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

